### ISSUE TITLE
[ENH]: Make blood output units similar to as specified in the _pet.json

### ISSUE THREAD

**Issue by mnoergaard** [mathesong/bloodstream#6]
Currently, the output of the blood data is in Bq/mL which is in line with the PET-BIDS specification. However, on multiple occasions I have experienced the PET data being in kBq/mL and not Bq/mL. It would be nice if a check could be made with the _pet.json file "Units" to verify that PET data and blood data units are consistent. Ideally, the output of the blood data should be similar to the units in the PET data.

**Comment by mathesong** [comment]
Thanks for the suggestion!  I spent quite some time thinking about how best to do this, and this was the compromise that I came to in the end.  So it was an intentional decision to do so - but I'll leave your issue up for a while in case there are things come up that I've not considered and I change my mind.  To be clear, I hate both seconds and Bq/mL as units for the output: I decided to produce everything in those units for consistency with both the specification and consistency across datasets.

To clarify my reasoning:

Firstly, when reading in the data, there are unit checks, and everything is converted to seconds and kBq.  So as input data, the units can be effectively [any radioactivity units](https://github.com/mathesong/kinfitr/blob/147398a25c876fcdd16b5d6ea1d7b1924355dcc7/R/kinfitr_miscfuncs.R#L500) and they're switched into my favourites.

Then, you'll notice that in the report itself, it switches around a little bit with units.  In the radioactivity plots (AIF and whole blood), the Y axis is kBq/mL because Bq is usually too difficult to read off (but with seconds on the X axis to help with identifying potential oddities in the data).  And then in the combined plots where the y units are scaled around 100%, then the X axis is in minutes because this is easier for relating to the biology in my opinion.

So then in the outputs, I had originally produced the values in kBq/mL and minutes because these most readable and easiest to work with.  Minutes are particularly important for the kinetic modelling, because the rate constants are measured in min<sup>-1</sup>, and many kinetic models will go completely awry if you send in values in seconds.  This makes the data easy to read, and more ready for kinetic modelling.  I scrapped this because this data (6000 rows) isn't really trying to optimise human readability, but machine-accessibility.

And, for machine accessibility, I figured it was most convenient to produce one single set of units across datasets, and for that, it was easier to choose that which was most consistent with the original BIDS-spec.  Moreover, by using seconds, this would even specifically *require* developers to fix them (seconds to minutes) for modelling.  I figured that this would push developers to pay attention to the units.  And then, by using the same units across datasets, it means that `bloodstream` outputs are more predictable, which ought to make it easier to develop tools around them.

So, when I implement `kinfitr` routines to read in this data, I would start off by reading out the units from the json sidecar and converting everything to minutes and kBq.  So it would work fine with dataset-specific units.  But if another developer is being a bit lazy and just assumes that those are the bloodstream units, then problems could ensue.  I feel that automating the unit conversion step so that others don't need to do any conversion is just a bit too dangerous, because I don't know what units the TACs will be in as their own derivative (depending on which processing pipeline was used to produce them), and assuming that the units are all sorted is doubtless going to lead to issues down the line.

As such, it's effectively *intentional* that the units of the outputs are a bit crappy, but consistent, as a reminder for developers who want to build around `bloodstream` outputs to pay attention to both the units of my output data, as well as the TACs :)
